# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-07 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusPlate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Placas Buses',
                'verbose_name': 'Placa Bus',
                'db_table': 'bus_plate',
            },
        ),
        migrations.CreateModel(
            name='BusPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bus_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BusPosition', to='backend.BusPlate')),
            ],
            options={
                'verbose_name_plural': 'Posiciones de Buses',
                'verbose_name': 'Posición de Bus',
                'db_table': 'bus_position',
            },
        ),
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Rutas Buses',
                'verbose_name': 'Ruta Bus',
                'db_table': 'bus_route',
            },
        ),
        migrations.CreateModel(
            name='BusSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='HorarioBuses')),
            ],
            options={
                'verbose_name_plural': 'Horario de Buses',
                'verbose_name': 'Horario de Buses',
                'db_table': 'bus_schedule',
            },
        ),
        migrations.AddField(
            model_name='busposition',
            name='bus_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BusPosition', to='backend.BusRoute'),
        ),
    ]
